### ISSUE TITLE
Does not work for Steam's Dota2

### ISSUE THREAD

**Issue by Paw2Pom** [mxrlkn/mouselock#11]
I just tried it on Steam's Dota2, and it doesn't seem to work.

Can we:
(1) Make it work on Steam's Dota2 as well
(2) Add a checkbox for "Steam's Dota2", just like we did for League of Legend.

OS: Ventura 13.0

Thank you!

**Comment by Paw2Pom** [comment]
It seems when I click "always", it mouselock also doesn't work and mouse can freely move between monitors...

OS: Ventura 13.0

**Comment by mxrlkn** [comment]
If it doesn't work on always, then it won't work in Dota. It works for me on Ventura.
Make sure you have the resolution set correctly.

**Comment by Paw2Pom** [comment]
After setting the resolution correctly, it works on "Always"!! Thank you so much!

**Comment by mxrlkn** [comment]
I added a checkbox for Dota in this test build. Can you check if it works?

https://github.com/mxrlkn/mouselock/suites/9236381324/artifacts/431762061

**Comment by Paw2Pom** [comment]
(1) The "Checkbox and Dota only" works
(2) I cannot get the correct resolution to work though, even I input the resolution "1728 x 1117", the mouse still get stuck at bottom of the screen. Is there anyway we can auto detect the screen resolution?

**Comment by mxrlkn** [comment]
Can't detect resolution. Does the mouse get stuck at the bottom only in the game, or also on "always" on the desktop?

Remember that it locks the mouse to the center of the screen, not the game window. So you need to have it in borderless. Having it windowed off center will not work.

**Comment by Paw2Pom** [comment]
It also stuck at the bottom only when in the game.

In desktop, when with "always" it works fine - mouse stuck in main window only.

**Comment by mxrlkn** [comment]
So I just tried Dota 2 myself. It seems to lock the mouse perfectly fine without this program in borderless mode.

I don't understand what you need mouselock for.

This is the problem mouselock solves: https://www.youtube.com/watch?v=LkT2M-CS-TM

**Comment by Paw2Pom** [comment]
Interesting. I just tried borderless mode, but my mouse can still move to other external monitors without using this program...

**Comment by mxrlkn** [comment]
Something else must be wrong with your setup. Maybe you have another mouse program running or something. Try another mouse or reinstalling the game.

**Comment by Paw2Pom** [comment]
Yes you are very correct! I have another program called "CatchMouse" running!
