### ISSUE TITLE
Please give a hand to CatchMouse

### ISSUE THREAD

**Issue by Paw2Pom** [mxrlkn/mouselock#13]
Hi mxrlkn,

I know this is not related to mouselock app, but I am a super big fan of using CatchMouse app:

https://github.com/round/CatchMouse/issues

But it seems the original owner don't support this amazing yet simple app.

Is there any chance you may give a hand on continuing making this app great and supported?

All of my friends are using this app, yet this app hasn't been updated for so long and started to have glitches in latest macOS (i.e. after each unplug of thunderbolt of external screens, the allocation of screens is misaligned so need to reset each time).

Btw the mouseLock works awesome! Thank you again for the amazing app makes our life much easier!

**Comment by mxrlkn** [comment]
No. Also that repo only contains the compiled app. It can't be supported.

**Comment by Paw2Pom** [comment]
Understood. Will it be very difficult to recreate such app?

<img width="800" alt="Screenshot 2022-12-08 at 9 55 13 AM" src="https://user-images.githubusercontent.com/21134942/206339655-43170062-75b6-4652-8dd5-938b26a64dd9.png">

There are quite a strong user base and demands for such a small app. Is there any chance we can somehow push for such project?

**Comment by mxrlkn** [comment]
I don't know. And I'm not going to make it, as I have no use for it.

**Comment by Paw2Pom** [comment]
Understood! Thank you so much!! :D Maybe one day!
