### ISSUE TITLE
Trackpad click drag erratic behavior.

### ISSUE THREAD

**Issue by pbobbert** [mxrlkn/mouselock#14]
There is a strange behavior that I have noticed while using the trackpad. Trying to click and drag causes the mouse to become erratic and skip, almost as if its dropping inputs or operate at a very low framerate. Consequently the trackpad feels unresponsive and seems to move about half the distance it should normally. This does not seem to happen when using a connected mouse, or as an experiment, while using the mouse to click and the trackpad to move. Tested on a 2017 intel macbook pro on 12.6.1

**Comment by mxrlkn** [comment]
Yeah I can see that. I haven't tested it with a trackpad. I'm not going to try and make it work because I don't play games with a trackpad, and I thought no one else did either.

What's your use case for using a trackpad with this app?
If you're playing video games with a trackpad I would recommend you to use a mouse instead.

**Comment by pbobbert** [comment]
My use case it to lock the mouse cursor to an external monitor, by setting the mouseLock app to the exact monitor resolution. There is actually no way by default in macOS to turn off your laptop display while using a plugged in monitor, unless you close the laptop lid (which means no keyboard and poor speaker performance). Mirroring the display does not work as it imposes strict and bad resolution restrictions (no HiDPI). So with this app I can "pretend" to only use one screen without worrying about getting my cursor lost on my laptop screen.

**Comment by mxrlkn** [comment]
I thought of a project I ran into recently that maybe could help you, and then I found you in the issues, ha. https://github.com/waydabber/BetterDisplay/issues/1232

I also remembered this project: https://lunar.fyi
There's a feature called BlackOut you could try.

**Comment by pbobbert** [comment]
Its funny you mention that, because I am using BetterDisplay, and because I showed this project to the author and he wants to implement it as a next major build feature.  The lunar blackout feature is a fake feature, it just sets the screen brightness to low and enables mirror mode, which as I mentioned above is no good (only apples knows why they limit this).

**Comment by mxrlkn** [comment]
oh okay, thats a bummer.

I gave him some inspiration. https://github.com/waydabber/BetterDisplay/discussions/1236#discussioncomment-4369848

I think fixing the trackpad issue would be a big thing to fix (I have no idea how) and doesn't really matter for this app as it's only made to fix games. I hope you get it into BetterDisplay :)

**Comment by pbobbert** [comment]
Oh cool! And I totally understand, I dont know how to fix it either lol. One thing that I have also noticed that might be of consequence to you is that under high load (or maybe high temperature is the culprit) both mouse and trackpad seem to skip occasionally. Perhaps the mouselock app is getting throttled before other things? Might not be an issue if you have a newer machine than mine.

**Comment by mxrlkn** [comment]
yeah it's very cpu heavy. It recalculates every mouse move constantly. I have an m1 mac so i'm fine. Apple won't make a simple API for this stuff so it's all a giant hack basically (Windows has one).

**Comment by pbobbert** [comment]
It doesnt seem to hog that much, highest I saw was 3.1%. Im still very happy to have it. There just seems to be a funny interaction when push comes to shove, mouselock gets shoved first. There is some weird thing going on with youtube and the hiDPI enabled resolution just cranking my temp all the way up to 70C, but mouselock is not the cause, more that it gets effected in a negative manner.
