### ISSUE TITLE
Mouse Position Update Optimization Query

### ISSUE THREAD

**Issue by ontimond** [mxrlkn/mouselock#16]
I have used the application a couple of times and would like to address a question, as I've noticed some peculiar mouse behavior within the application (League of Legends). It's a bit challenging to detect this movement, but it becomes noticeable on certain occasions. I understand that the idea is to update the mouse position when it leaves the application's area or the screen resolution. After examining the code and logic a bit, I would like to clarify this doubt: Is the mouse position updated every time it moves, or is there a validation to determine when it has actually left the area? In the latter case, there should be no need to update the position, preventing unnecessary updates whenever a movement event is triggered

**Comment by mxrlkn** [comment]
It updates the position on every movement yes. I couldn't get it to work otherwise. Check my answer here: https://github.com/mxrlkn/mouselock/issues/17#issuecomment-1837588789

**Comment by mxrlkn** [comment]
closing this for #17
