### ISSUE TITLE
This is exactly what I was looking for, thank you so much !

### ISSUE THREAD

**Issue by Trepleu** [mxrlkn/mouselock#18]
Even with LoL in full screen, my cursor kept going small (I play in 4K) when hitting the edge...
I was resigned to use only 1 screen but this change everything !

**Comment by mxrlkn** [comment]
Good to hear :)

**Comment by jonpurdy** [comment]
Adding to this, and using this for my toddler (now 3 years old actually) for every program she uses. I place the windows I need (like KidPix running in an emulator)  in the center of the screen with black background and set the size in mouselock to the size of the window. No more losing the cursor! 

Thank you @mxrlkn 👍
