### ISSUE TITLE
Sonoma - Apple cannot check for malicious software

### ISSUE THREAD

**Issue by ncermesoni** [mxrlkn/mouselock#20]
When launching the app on macos 14.6.1, I get the following error message: mouselock can't be opened because Apple cannot check it for malicious software.
<img width="469" alt="image" src="https://github.com/user-attachments/assets/3740c691-300e-4903-ba70-7488283bb2c6">

Any idea how to fix?

**Comment by mxrlkn** [comment]
right-click the app and click "open", then you should get the option to open it anyway.
You should be able to open it like normal after that.

**Comment by mxrlkn** [comment]
I assume that fixed it :)

**Comment by ncermesoni** [comment]
@mxrlkn it did, thank you very much! I forgot to report back, sorry!
