### ISSUE TITLE
Mouselock crashes with Wine and League of Legends option ticked

### ISSUE THREAD

**Issue by relalis** [mxrlkn/mouselock#3]
Steps to reproduce:

1. Launch mouselock
2. Execute any wine command to start wineserver (e.g. WINEPREFIX=~/.testing-wine wine64 winecfg)

Console output from debug binary (xcodebuild -quiet -configuration Debug -target mouselock):
`mouselock/mouselockApp.swift:62: Fatal error: Unexpectedly found nil while unwrapping an Optional value`
`zsh: illegal hardware instruction  ./build/Debug/mouselock.app/Contents/MacOS/mouselock`

It's probably worth noting that this is reproducible on both wine-crossover from Gcenx/homebrew-wine, and a fresh wine64 build, both on macOS 12.1

**Comment by relalis** [comment]
Error is reproducible when mouselock is disabled, and when "League of Legends" is checked, but mouselock does not crash when "Always" is checked in the "Activate" section

**Comment by mxrlkn** [comment]
Can you try and replace line 62 with this and see if that fixes it?

```
if (AppState.shared.active == false && (AppState.shared.activegames[(NSWorkspace().frontmostApplication?.bundleIdentifier ?? "")] ?? false) == false) {
```

**Comment by relalis** [comment]
yep, that did the trick. want me to submit a PR?

**Comment by mxrlkn** [comment]
Yeah thats fine. I'll make a new release after.

**Comment by relalis** [comment]
If you're gonna push a new release anyway, I might as well leave it up to you.
