### ISSUE TITLE
version locked to monterey

### ISSUE THREAD

**Issue by rhysmorgan134** [mxrlkn/mouselock#5]
Awesome bit of software, thanks alot for it! Recently got rid of the gaming pc and went solely Mac, and this has saved me from having to bootcamp to play league! I am sure you are aware, but it requires monterey to install, I did try and build on big sur, but it still needed monterey, I upgraded in the end, so all good, but might be nice for people that don't want to run a beta.

Thanks again!

**Comment by mxrlkn** [comment]
I had no idea it was version locked. Thanks for the heads up. I'm pretty new to xcode so it isn't intentional. I'll look into it and see if I can open it up to more versions.

**Comment by mxrlkn** [comment]
It now requires MacOS 11.0 or later. https://github.com/mxrlkn/mouselock/releases/tag/v0.0.9
